# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25f8d6032dd4664de0d3750853524c60f78d7a335fba709c9659fcb2a0a8e1404bf2206c757e4981b3e6eedb92f4ca00fdba6c06b95765ecf3e2cde9d9327f38
  github_key: YOUR_GITHUB_KEY
  github_secret: YOUR_GITHUB_SECRET
  ssh_passphrase: YOUR_SSH_PASSPHRASE
  ssh_private_key: YOUR_SSH_PRIVATE_KEY_PASSWORD

test:
  secret_key_base: 8e12005510381a8bc4f860f3c97f0d6481e35ab5b8b189e9d468352b81d293860d0cb073a966b746a0e35eef9f71f64da5c186fef82cd039fadf120b8ba88078
  github_key: YOUR_GITHUB_KEY
  github_secret: YOUR_GITHUB_SECRET
  ssh_passphrase: YOUR_SSH_PASSPHRASE
  ssh_private_key: YOUR_SSH_PRIVATE_KEY_PASSWORD

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_key: YOUR_GITHUB_KEY
  github_secret: YOUR_GITHUB_SECRET
  ssh_passphrase: YOUR_SSH_PASSPHRASE
  ssh_private_key: YOUR_SSH_PRIVATE_KEY_PASSWORD
